FROM python:2
ENV PYTHONUNBUFFERED=1
COPY requirements.txt /usr/src/app/
COPY test-requirements.txt /usr/src/app/
WORKDIR /usr/src/app
RUN pip install -r requirements.txt -r test-requirements.txt
COPY . /usr/src/app
RUN python setup.py install
